# Generated by Django 5.0.1 on 2024-01-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='title',
            new_name='book',
        ),
    ]
