# Generated by Django 5.0.1 on 2024-01-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='borrowing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
