# Generated by Django 5.0.1 on 2024-01-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_purchase_borrowing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
